#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$BASE_DIR/../src"
DIST_DIR="$BASE_DIR/../dist"
PACKAGE_FILE="$BASE_DIR/../package.json"

version=$(jq -r '.version' "$PACKAGE_FILE")

echo "Minify schemas (version ${version})."

mkdir -p "$DIST_DIR"

for f in "$SRC_DIR"/*.json; do

  [ -f "$f" ] || continue

  name=$(basename "$f" .json)
  echo "  Minify ${name}.json"

  id="https://cdn.hopjs.net/npm/@dicebear/schema@${version}/dist/${name}.min.json"
  jq -c --arg id "$id" '{"$id": $id} + .' "$f" > "$DIST_DIR/${name}.min.json"

done

echo "Generate Dart package (lib/dicebear_schema.dart)."

DART_FILE="$BASE_DIR/../lib/dicebear_schema.dart"
mkdir -p "$BASE_DIR/../lib"

# Schema names, sorted under LC_ALL=C so the generated order is byte-stable
# across machines/locales. lib/ is git-ignored and rebuilt for every publish,
# so the test job's parity check and the published package must not depend on
# the build machine's locale.
names=()
while IFS= read -r name; do
  names+=("$name")
done < <(
  for f in "$SRC_DIR"/*.json; do
    [ -f "$f" ] || continue
    basename "$f" .json
  done | LC_ALL=C sort
)

# Dart has no include_str!/go:embed, so unlike the hand-written schema.rs and
# schema.go, the Dart shim must be generated: the JSON is embedded as string
# literals. Escape for a non-raw triple-quoted Dart string ('''…'''): backslash
# first, then the quote and `$` (string interpolation). The escaped literal
# restores the exact source bytes, so the constants stay byte-identical to
# src/*.json (tool/check_parity.dart proves this in CI). The JSON files start
# with `{`, which matters: Dart strips a newline that directly follows the
# opening ''' delimiter. LC_ALL=C processes the UTF-8 bytes as-is (the patterns
# are pure ASCII); without it, BSD sed errors out on byte sequences that are
# invalid in the active locale.
dart_escape() { LC_ALL=C sed -e 's/\\/\\\\/g' -e "s/'/\\\\'/g" -e 's/\$/\\$/g'; }

{
  # Generated-marker and library docs (static); the repository's root LICENSE
  # (MIT) covers the generated file, so it carries no license header of its
  # own. A quoted heredoc writes `$` and backticks verbatim.
  cat <<'EOF'
// @generated by scripts/build.sh from src/*.json — do not edit by hand.

/// DiceBear JSON Schema definitions, embedded as Dart string constants.
///
/// This is a pure-data package. It mirrors the npm (`@dicebear/schema`),
/// Composer, PyPI, crates.io and Go packages: the same source schemas, with no
/// logic. Consumers parse and validate (e.g. with `package:json_schema`); this
/// package only ships the bytes.
library;

EOF

  for name in "${names[@]}"; do
    printf '/// Raw JSON of the DiceBear `%s` schema (src/%s.json).\n' "$name" "$name"
    printf "const String %s = '''" "$name"
    dart_escape < "$SRC_DIR/$name.json"
    printf "''';\n\n"
  done

  cat <<'EOF'
/// Returns the raw JSON for the named schema, or `null` if the name is
/// unknown.
String? get(String name) {
  switch (name) {
EOF
  for name in "${names[@]}"; do
    printf "    case '%s':\n      return %s;\n" "$name" "$name"
  done
  cat <<'EOF'
  }
  return null;
}

/// Names of every embedded schema, sorted.
///
/// Companion to `get`: `all` lists the names, `get(name)` fetches one.
const List<String> all = [
EOF
  for name in "${names[@]}"; do
    printf "  '%s',\n" "$name"
  done
  echo "];"
} > "$DART_FILE"
